using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;

namespace SourceGenerator
{
    internal static class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:未使用のパラメーターを削除します", Justification = "非公開の内部コマンドのMainメソッドであり、将来パラメタが使用される可能性があるため。")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("CodeQuality", "IDE0079:不要な抑制を削除します", Justification = "パラメタが追加された場合にIDE0060が発生してしまうため。")]
        private static void Main()
        {
            var baseDirectoryPath = new FileInfo(typeof(Program).Assembly.Location).Directory?.Parent?.Parent?.Parent?.Parent ?? throw new Exception();
            if (baseDirectoryPath.Name != "Game.GameSolver")
                throw new Exception();

            GenerateSudokuSolver(Path.Combine(baseDirectoryPath.FullName, "Game.SudokuSolver.GUI"));

            Console.WriteLine("Completed.");
            Console.Beep();
            _ = Console.ReadLine();
        }

        private static void GenerateSudokuSolver(string coreProjectPath)
        {
            GenerateBoardCellGeometry(coreProjectPath);
            GenerateBoardCellsSet(coreProjectPath);

            static void GenerateBoardCellsSet(string coreProjectPath)
            {
                var outputPath = Path.Combine(coreProjectPath, "BoardCellsSet.AutoGenerated.cs");
                if (File.Exists(outputPath))
                {
                    var outputFileAttribute = File.GetAttributes(outputPath);
                    File.SetAttributes(outputPath, outputFileAttribute & ~FileAttributes.ReadOnly);
                }

                try
                {
                    using var sourceWriter = new StreamWriter(outputPath, false, Encoding.UTF8);
                    sourceWriter.WriteLine("namespace Game.SudokuSolver.GUI");
                    sourceWriter.WriteLine("{");
                    sourceWriter.WriteLine("    internal partial class BoardCellsSet");
                    sourceWriter.WriteLine("    {");
                    sourceWriter.WriteLine("        private static readonly byte[][] _visibleCellsIndexes =");
                    sourceWriter.WriteLine("        [");

                    for (var cellIndex = 0; cellIndex < 81; ++cellIndex)
                    {
                        var column = cellIndex % 9;
                        var row = cellIndex / 9;
                        var blockColumn = column / 3;
                        var blockRow = row / 3;
                        var indexList = new List<int>();

                        // 横方向のハウスのインデックスの追加
                        for (var count = 0; count < 9; ++count)
                        {
                            var index = row * 9 + count;
                            if (index != cellIndex)
                            {
                                if (index is < 0 or >= 81)
                                    throw new ApplicationException();
                                indexList.Add(index);
                            }
                        }

                        // 縦方向のハウスのインデックスの追加
                        for (var count = 0; count < 9; ++count)
                        {
                            var index = column + count * 9;
                            if (index != cellIndex)
                            {
                                if (index is < 0 or >= 81)
                                    throw new ApplicationException();
                                indexList.Add(index);
                            }
                        }

                        // ブロックのインデックスの追加
                        for (var rowCount = 0; rowCount < 3; ++rowCount)
                        {
                            for (var columnCount = 0; columnCount < 3; ++columnCount)
                            {
                                var index = blockRow * 27 + blockColumn * 3 + rowCount * 9 + columnCount;
                                if (index != cellIndex)
                                {
                                    if (index is < 0 or >= 81)
                                        throw new ApplicationException();
                                    indexList.Add(index);
                                }
                            }
                        }

                        sourceWriter.WriteLine($"            [ {string.Join(", ", indexList.Distinct().OrderBy(n => n).Select(n => $"{n:D2}"))} ],");
                    }

                    sourceWriter.WriteLine("        ];");
                    sourceWriter.WriteLine("    }");
                    sourceWriter.WriteLine("}");
                }
                finally
                {
                    var outputFileAttribute = File.GetAttributes(outputPath);
                    File.SetAttributes(outputPath, outputFileAttribute | FileAttributes.ReadOnly);
                }
            }

            static void GenerateBoardCellGeometry(string coreProjectPath)
            {
                var outputPath = Path.Combine(coreProjectPath, "BoardCellGeometry.AutoGenerated.cs");
                if (File.Exists(outputPath))
                {
                    var outputFileAttribute = File.GetAttributes(outputPath);
                    File.SetAttributes(outputPath, outputFileAttribute & ~FileAttributes.ReadOnly);
                }

                try
                {
                    using var sourceWriter = new StreamWriter(outputPath, false, Encoding.UTF8);
                    sourceWriter.WriteLine("using System;");
                    sourceWriter.WriteLine();
                    sourceWriter.WriteLine("namespace Game.SudokuSolver.GUI");
                    sourceWriter.WriteLine("{");
                    sourceWriter.WriteLine("    internal static partial class BoardCellGeometry");
                    sourceWriter.WriteLine("    {");

                    #region _columnHouseCellsBitMasksByCellIndex
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字のセルと列を同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _columnHouseCellsBitMasksByCellIndex =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.column == item.cell2.column)
                            .Select(item => (item.cell1.cellIndex, otherCellIndex: item.cell2.cellIndex))
                            .GroupBy(item => item.cellIndex)
                            .Select(g => (cellIndex: g.Key, bitsOfCellOtherIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.otherCellIndex))))
                            .Distinct()
                            .OrderBy(item => item.cellIndex)
                            .Select(item => item.bitsOfCellOtherIndex)
                            .ToArray();
                        if (source.Length != 81)
                            throw new ApplicationException();
                        for (var index1 = 0; index1 < 9; ++index1)
                            sourceWriter.WriteLine($"            {string.Join(", ", Enumerable.Range(0, 9).Select(index2 => FormatUInt128Constant(source[index1 * 9 + index2])))},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _columnHouseCellsBitMasksByColumn
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字の列と列を同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _columnHouseCellsBitMasksByColumn =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.column == item.cell2.column)
                            .Select(item => (item.cell1.column, item.cell2.cellIndex))
                            .Distinct()
                            .GroupBy(item => item.column)
                            .Select(g => (column: g.Key, bitsOfCellIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.cellIndex))))
                            .Distinct()
                            .OrderBy(item => item.column)
                            .Select(item => item.bitsOfCellIndex)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            {FormatUInt128Constant(source[index])},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _rowHouseCellsBitMasksByCellIndex
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字のセルと行を同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _rowHouseCellsBitMasksByCellIndex =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.row == item.cell2.row)
                            .Select(item => (item.cell1.cellIndex, otherCellIndex: item.cell2.cellIndex))
                            .GroupBy(item => item.cellIndex)
                            .Select(g => (cellIndex: g.Key, bitsOfOtherCellIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.otherCellIndex))))
                            .OrderBy(item => item.cellIndex)
                            .Select(item => item.bitsOfOtherCellIndex)
                            .ToArray();
                        if (source.Length != 81)
                            throw new ApplicationException();
                        for (var index1 = 0; index1 < 9; ++index1)
                            sourceWriter.WriteLine($"            {string.Join(", ", Enumerable.Range(0, 9).Select(index2 => FormatUInt128Constant(source[index1 * 9 + index2])))},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _rowHouseCellsBitMasksByRow
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字の行と行を同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _rowHouseCellsBitMasksByRow =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.row == item.cell2.row)
                            .Select(item => (item.cell1.row, item.cell2.cellIndex))
                            .Distinct()
                            .GroupBy(item => item.row)
                            .Select(g => (row: g.Key, bitsOfOtherCellIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.cellIndex))))
                            .Distinct()
                            .OrderBy(item => item.row)
                            .Select(item => item.bitsOfOtherCellIndex)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            {FormatUInt128Constant(source[index])},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _blockHouseCellsBitMasksByCellIndex
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字のセルとブロックを同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _blockHouseCellsBitMasksByCellIndex =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.block == item.cell2.block)
                            .Select(item => (item.cell1.cellIndex, otherCellIndex: item.cell2.cellIndex))
                            .GroupBy(item => item.cellIndex)
                            .Select(g => (cellIndex: g.Key, bitsOfOtherCellIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.otherCellIndex))))
                            .OrderBy(item => item.cellIndex)
                            .Select(item => item.bitsOfOtherCellIndex)
                            .ToArray();
                        if (source.Length != 81)
                            throw new ApplicationException();
                        for (var index1 = 0; index1 < 9; ++index1)
                            sourceWriter.WriteLine($"            {string.Join(", ", Enumerable.Range(0, 9).Select(index2 => FormatUInt128Constant(source[index1 * 9 + index2])))},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _blockHouseCellsBitMasksByBlock
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字のブロックとブロックを同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _blockHouseCellsBitMasksByBlock =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.block == item.cell2.block)
                            .Select(item => (item.cell1.block, item.cell2.cellIndex))
                            .Distinct()
                            .GroupBy(item => item.block)
                            .Select(g => (block: g.Key, bitsOfOtherCellIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.cellIndex))))
                            .Distinct()
                            .OrderBy(item => item.block)
                            .Select(item => item.bitsOfOtherCellIndex)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            {FormatUInt128Constant(source[index])},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _visibleCellsBitMasksByCellIndex
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 添え字のセルと行、列、ブロックの何れかを同じくするセルの集合。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly UInt128[] _visibleCellsBitMasksByCellIndex =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .SelectMany(cell1 => EnumerateDetailOfCellGeometry(), (cell1, cell2) => (cell1, cell2))
                            .Where(item => item.cell1.block == item.cell2.block || item.cell1.column == item.cell2.column || item.cell1.row == item.cell2.row)
                            .Select(item => (item.cell1.cellIndex, otherCellIndex: item.cell2.cellIndex))
                            .GroupBy(item => item.cellIndex)
                            .Select(g => (cellIndex: g.Key, bitsOfOtherCellIndex: g.Aggregate(UInt128.Zero, (result, item) => result | (UInt128.One << item.otherCellIndex))))
                            .OrderBy(item => item.cellIndex)
                            .Select(item => item.bitsOfOtherCellIndex)
                            .ToArray();
                        if (source.Length != 81)
                            throw new ApplicationException();
                        for (var index1 = 0; index1 < 9; ++index1)
                            sourceWriter.WriteLine($"            {string.Join(", ", Enumerable.Range(0, 9).Select(index2 => FormatUInt128Constant(source[index1 * 9 + index2])))},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _columnsByBlock
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// ブロックハウスと重なる列の集合。第一添え字はブロック、第二添え字はブロック内の列のオフセット値。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly BoardCellColumn[][] _columnsByBlock =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .Select(item => (item.block, item.column))
                            .Distinct()
                            .GroupBy(item => item.block)
                            .Select(g => (block: g.Key, columns: g.Select(item => item.column).ToArray()))
                            .OrderBy(item => item.block)
                            .Select(item => item.columns)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            [{string.Join(", ", source[index].Select(row => $"BoardCellColumn.One + {row}"))}],");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _rowsByBlock
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// ブロックハウスと重なる行の集合。第一添え字はブロック、第二添え字はブロック内の行のオフセット値。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly BoardCellRow[][] _rowsByBlock =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .Select(item => (item.block, item.row))
                            .Distinct()
                            .GroupBy(item => item.block)
                            .Select(g => (block: g.Key, rows: g.Select(item => item.row).ToArray()))
                            .OrderBy(item => item.block)
                            .Select(item => item.rows)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            [{string.Join(", ", source[index].Select(row => $"BoardCellRow.One + {row}"))}],");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _blocksByColumn
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 列ハウスと重なるブロックの集合。第一添え字は列、第二添え字は 0 から 2 の整数。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly BoardCellBlock[][] _blocksByColumn =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .Select(item => (item.column, item.block))
                            .Distinct()
                            .GroupBy(item => item.column)
                            .Select(g => (column: g.Key, blocks: g.Select(item => item.block).ToArray()))
                            .OrderBy(item => item.column)
                            .Select(item => item.blocks)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            [{string.Join(", ", source[index].Select(row => $"BoardCellBlock.FirstValue + {row}"))}],");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _blocksByRow
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 行ハウスと重なるブロックの集合。第一添え字は行、第二添え字は 0 から 2 の整数。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly BoardCellBlock[][] _blocksByRow =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .Select(item => (item.row, item.block))
                            .Distinct()
                            .GroupBy(item => item.row)
                            .Select(g => (row: g.Key, blocks: g.Select(item => item.block).ToArray()))
                            .OrderBy(item => item.row)
                            .Select(item => item.blocks)
                            .ToArray();
                        if (source.Length != 9)
                            throw new ApplicationException();
                        for (var index = 0; index < 9; ++index)
                            sourceWriter.WriteLine($"            [{string.Join(", ", source[index].Select(row => $"BoardCellBlock.FirstValue + {row}"))}],");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _cellIndexByRowColumn
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// 行・列からセル番号への変換テーブル。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly BoardCellIndex[] _cellIndexByRowColumn =");
                        sourceWriter.WriteLine("        [");
                        for (var index1 = 0; index1 < 16; ++index1)
                            sourceWriter.WriteLine($"            {string.Join(", ", Enumerable.Range(0, 16).Select(index2 => index1 < 9 && index2 < 9 ? $"BoardCellIndex.FirstValue + {index1 * 9 + index2}" : "BoardCellIndex.Undefined"))},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine();

                    #region _columnRowBlockByCellIndex
                    {
                        sourceWriter.WriteLine("        /// <summary>");
                        sourceWriter.WriteLine("        /// セル番号から列・行・ブロックへの変換テーブル。");
                        sourceWriter.WriteLine("        /// </summary>");
                        sourceWriter.WriteLine("        private static readonly (BoardCellColumn column, BoardCellRow row, BoardCellBlock block)[] _columnRowBlockByCellIndex =");
                        sourceWriter.WriteLine("        [");
                        var source =
                            EnumerateDetailOfCellGeometry()
                            .Select(item => (item.cellIndex, item.column, item.row, item.block))
                            .Distinct()
                            .OrderBy(item => item.cellIndex)
                            .Select(item => (item.column, item.row, item.block))
                            .ToArray();
                        for (var index1 = 0; index1 < 9; ++index1)
                            sourceWriter.WriteLine($"            {string.Join(", ", Enumerable.Range(0, 9).Select(index2 => $"(BoardCellColumn.One + {source[index1 * 9 + index2].column}, BoardCellRow.One + {source[index1 * 9 + index2].row}, BoardCellBlock.FirstValue + {source[index1 * 9 + index2].block})"))},");
                        sourceWriter.WriteLine("        ];");
                    }
                    #endregion

                    sourceWriter.WriteLine("    }");
                    sourceWriter.WriteLine("}");
                }
                finally
                {
                    var outputFileAttribute = File.GetAttributes(outputPath);
                    File.SetAttributes(outputPath, outputFileAttribute | FileAttributes.ReadOnly);
                }

                static IEnumerable<(int cellIndex, int column, int row, int blockColumn, int blockRow, int block)> EnumerateDetailOfCellGeometry()
                {
                    return
                        Enumerable.Range(0, 81)
                        .Select(cellIndex => (cellIndex, column: cellIndex % 9, row: cellIndex / 9))
                        .Select(item => (item.cellIndex, item.column, item.row, blockColumn: item.column / 3, blockRow: item.row / 3))
                        .Select(item => (item.cellIndex, item.column, item.row, item.blockColumn, item.blockRow, block: item.blockRow * 3 + item.blockColumn));
                }

                static string FormatUInt128Constant(UInt128 value)
                {
                    return $"new UInt128(0x{(value >> 64) & ulong.MaxValue:x16}ul, 0x{value & ulong.MaxValue:x16}ul)";
                }
            }
        }
    }
}
